/**
 * Icon Manifest — Source of truth for vendored Central Icons
 *
 * To add a new icon:
 *   1. Add an entry to ICON_MANIFEST below
 *   2. Run `npm run icons:extract` (requires CENTRAL_LICENSE_KEY)
 *   3. Commit the generated file in src/components/Icon/icons/
 *
 * To update all icons to the latest Central Icons version:
 *   1. Run `npm update @central-icons-react/round-outlined-radius-3-stroke-1.5 @central-icons-react/round-outlined-radius-0-stroke-1.5 @central-icons-react/round-filled-radius-3-stroke-1.5`
 *   2. Run `npm run icons:extract`
 *   3. Commit the updated files
 */

export type IconVariant = 'outlined' | 'sharp' | 'filled';

export type IconEntry = {
  /** Central Icons component name (e.g. "IconArrow") */
  name: string;
  /** Which variant package to extract from. Defaults to "outlined" */
  variant?: IconVariant;
  /** Name to export as in Origin. Defaults to name */
  exportAs?: string;
};

export const ICON_MANIFEST: IconEntry[] = [
  // ── Pure directional arrows (sharp/radius-0) ────────────────
  { name: 'IconArrow', variant: 'sharp' },
  { name: 'IconArrowDown', variant: 'sharp' },
  { name: 'IconArrowDownLeft', variant: 'sharp' },
  { name: 'IconArrowDownRight', variant: 'sharp' },
  { name: 'IconArrowLeft', variant: 'sharp' },
  { name: 'IconArrowRight', variant: 'sharp' },
  { name: 'IconArrowUp', variant: 'sharp' },
  { name: 'IconArrowUpLeft', variant: 'sharp' },
  { name: 'IconArrowUpRight', variant: 'sharp' },
  { name: 'IconRedirectArrow', variant: 'sharp' },

  // ── Pure directional chevrons (sharp/radius-0) ─────────────
  { name: 'IconChevronBottom', variant: 'sharp' },
  { name: 'IconChevronDownSmall', variant: 'sharp' },
  { name: 'IconChevronGrabberVertical', variant: 'sharp' },
  { name: 'IconChevronLeft', variant: 'sharp' },
  { name: 'IconChevronLeftSmall', variant: 'sharp' },
  { name: 'IconChevronRight', variant: 'sharp' },
  { name: 'IconChevronRightSmall', variant: 'sharp' },
  { name: 'IconChevronTop', variant: 'sharp' },
  { name: 'IconChevronTopSmall', variant: 'sharp' },

  // ── Compound arrow variants (outlined/radius-3) ────────────
  { name: 'IconArrowBoxRight' },
  { name: 'IconArrowDownSquare' },
  { name: 'IconArrowDownWall' },
  { name: 'IconArrowInbox' },
  { name: 'IconArrowLeftSquare' },
  { name: 'IconArrowLoopDownLeft' },
  { name: 'IconArrowOutOfBox' },
  { name: 'IconArrowRightSquare' },
  { name: 'IconArrowUpSquare' },
  { name: 'IconArrowUpWall' },
  { name: 'IconArrowsRepeat' },
  { name: 'IconArrowsRepeatCircle' },
  { name: 'IconRotate360Left' },
  { name: 'IconRotate360Right' },

  // ── UI Actions ─────────────────────────────────────────────
  { name: 'IconAdjustPhoto' },
  { name: 'IconAt' },
  { name: 'IconAutoCrop' },
  { name: 'IconBarsThree2' },
  { name: 'IconBell' },
  { name: 'IconBellOff' },
  { name: 'IconBlackpoint' },
  { name: 'IconBrackets1' },
  { name: 'IconBrokenHeart' },
  { name: 'IconBrowserTabs' },
  { name: 'IconBubble3' },
  { name: 'IconBubbleWideSparkle' },
  { name: 'IconCalendarDays' },
  { name: 'IconCheckmark2' },
  { name: 'IconCheckmark2Small' },
  { name: 'IconCircleCheck' },
  { name: 'IconCircleInfo' },
  { name: 'IconCirclePlus' },
  { name: 'IconCircleQuestionmark' },
  { name: 'IconCircleCheck', variant: 'filled', exportAs: 'IconCircleCheckFilled' },
  { name: 'IconCircleInfo', variant: 'filled', exportAs: 'IconCircleInfoFilled' },
  { name: 'IconCircleX', variant: 'filled' },
  { name: 'IconHeart2', variant: 'filled', exportAs: 'IconHeart2Filled' },
  { name: 'IconOngoing', variant: 'filled', exportAs: 'IconOngoingFilled' },
  { name: 'IconPeople2', variant: 'filled', exportAs: 'IconPeople2Filled' },
  { name: 'IconClipboard2' },
  { name: 'IconClipboard2Sparkle' },
  { name: 'IconClock' },
  { name: 'IconCmdBox' },
  { name: 'IconConnectors1' },
  { name: 'IconConnectors2' },
  { name: 'IconConsoleSparkle' },
  { name: 'IconCrossLarge' },
  { name: 'IconCrossSmall' },
  { name: 'IconCryptoWallet' },
  { name: 'IconDevices' },
  { name: 'IconDiamondShine' },
  { name: 'IconDifferenceIgnored' },
  { name: 'IconDifferenceModified' },
  { name: 'IconDiscoBall' },
  { name: 'IconDotGrid1x3Horizontal' },
  { name: 'IconDotGrid1x3HorizontalTight' },
  { name: 'IconDotGrid1x3Vertical' },
  { name: 'IconDotGrid1x3VerticalTight' },
  { name: 'IconDotGrid2x3' },
  { name: 'IconDotGrid3x3' },
  { name: 'IconExclamationTriangle' },
  { name: 'IconExclamationTriangle', variant: 'filled', exportAs: 'IconExclamationTriangleFilled' },
  { name: 'IconEyeOpen' },
  { name: 'IconEyeSlash' },
  { name: 'IconEyeSlash2' },
  { name: 'IconFileArrowLeftIn' },
  { name: 'IconFileArrowLeftOut' },
  { name: 'IconFileArrowRightOut' },
  { name: 'IconFileBend' },
  { name: 'IconFilter2' },
  { name: 'IconFingerPrint1' },
  { name: 'IconFormPyramide' },
  { name: 'IconForYou' },
  { name: 'IconFullScreen' },
  { name: 'IconGlobe2' },
  { name: 'IconHeart2' },
  { name: 'IconHome' },
  { name: 'IconImport2' },
  { name: 'IconInitiatives' },
  { name: 'IconInvite' },
  { name: 'IconKey2' },
  { name: 'IconLayoutColumn' },
  { name: 'IconLayoutLeft' },
  { name: 'IconLayoutRight' },
  { name: 'IconListSparkle' },
  { name: 'IconLiveActivity' },
  { name: 'IconLiveFull' },
  { name: 'IconLoader' },
  { name: 'IconLock' },
  { name: 'IconMagnifyingGlass2' },
  { name: 'IconMinusLarge' },
  { name: 'IconMinusSmall' },
  { name: 'IconMoon' },
  { name: 'IconMouse' },
  { name: 'IconOffline' },
  { name: 'IconOngoing' },
  { name: 'IconPaperclip1' },
  { name: 'IconPassport' },
  { name: 'IconPassword' },
  { name: 'IconPasswordStars' },
  { name: 'IconPencil' },
  { name: 'IconPencil2' },
  { name: 'IconPencil3' },
  { name: 'IconPencilAi' },
  { name: 'IconPeople2' },
  { name: 'IconPeopleCircle' },
  { name: 'IconPeopleIdCard' },
  { name: 'IconPhone' },
  { name: 'IconPhoneDynamicIsland' },
  { name: 'IconPlusLarge' },
  { name: 'IconPlusSmall' },
  { name: 'IconPrompt' },
  { name: 'IconRandom' },
  { name: 'IconRemix' },
  { name: 'IconRemoveKeyframe' },
  { name: 'IconRepeat' },
  { name: 'IconRescueRing' },
  { name: 'IconRunShortcut' },
  { name: 'IconScanCode' },
  { name: 'IconSearchIntelligence' },
  { name: 'IconSearchlinesSparkle' },
  { name: 'IconSecretPhrase' },
  { name: 'IconSettingsGear1' },
  { name: 'IconSettingsGear2' },
  { name: 'IconShield' },
  { name: 'IconShield2' },
  { name: 'IconShieldKeyhole' },
  { name: 'IconSidebarSimpleLeftWide' },
  { name: 'IconSpacebar' },
  { name: 'IconSquareBehindSquare1' },
  { name: 'IconSquareBehindSquare6' },
  { name: 'IconSquareInfo' },
  { name: 'IconSquarePlus' },
  { name: 'IconSticker' },
  { name: 'IconSun' },
  { name: 'IconStop' },
  { name: 'IconStopCircle' },
  { name: 'IconTag' },
  { name: 'IconTarget' },
  { name: 'IconTelescope' },
  { name: 'IconTextToSpeach' },
  { name: 'IconTextareaDrag' },
  { name: 'IconTimeFlies' },
  { name: 'IconTimeslot' },
  { name: 'IconToggle' },
  { name: 'IconTrashCanSimple' },
  { name: 'IconTrashRounded' },
  { name: 'IconUnblur' },
  { name: 'IconUsbC' },
  { name: 'IconVariables' },
  { name: 'IconWallet1' },
  { name: 'IconWallet3' },
  { name: 'IconWeb3' },
  { name: 'IconWindowSparkle' },
  { name: 'IconWreathSimple' },

  // ── AI & Sparkle ───────────────────────────────────────────
  { name: 'IconAgenticCoding' },
  { name: 'IconImagineAi' },
  { name: 'IconVibeCoding2' },
  { name: 'IconVisualIntelligence' },

  // ── Voice ──────────────────────────────────────────────────
  { name: 'IconVoiceHigh' },
  { name: 'IconVoiceLow' },
  { name: 'IconVoiceMid' },
  { name: 'IconVoiceRecord' },
  { name: 'IconVoiceSettings' },
  { name: 'IconVoiceSparkle' },

  // ── User & People ─────────────────────────────────────────
  { name: 'IconUserAdded' },
  { name: 'IconUserAddRight' },
  { name: 'IconUserBlock' },
  { name: 'IconUserDuo' },
  { name: 'IconUserEdit' },
  { name: 'IconUserGroup' },
  { name: 'IconUserRemove' },
  { name: 'IconUserRemoveRight' },
  { name: 'IconUserSettings' },

  // ── Brands & Logos ─────────────────────────────────────────
  { name: 'IconAntigravity' },
  { name: 'IconApple' },
  { name: 'IconBitcoinLogo' },
  { name: 'IconClaudeai' },
  { name: 'IconCursor' },
  { name: 'IconEuropeanUnion' },
  { name: 'IconGemini' },
  { name: 'IconGithub' },
  { name: 'IconGrok' },
  { name: 'IconIsoOrg' },
  { name: 'IconLinear' },
  { name: 'IconLinkedin' },
  { name: 'IconNotion' },
  { name: 'IconOpenai' },
  { name: 'IconSlack' },
  { name: 'IconSupabase' },
  { name: 'IconTwitter' },
  { name: 'IconV0' },
  { name: 'IconVercel' },
];
