export {
  useSidebar,
  Provider,
  Root,
  Trigger,
  Header,
  Content,
  Footer,
  Group,
  GroupHeader,
  Items,
  Item,
  ExpandableItem,
  SubmenuItem,
  DrilldownItem,
  TreeItem,
  Separator,
} from './parts';

export type {
  ProviderProps,
  RootProps,
  TriggerProps,
  HeaderProps,
  ContentProps,
  FooterProps,
  GroupProps,
  GroupHeaderProps,
  ItemsProps,
  ItemProps,
  ExpandableItemProps,
  SubmenuItemProps,
  DrilldownItemProps,
  TreeItemProps,
  SeparatorProps,
} from './parts';

import {
  useSidebar,
  Provider,
  Root,
  Trigger,
  Header,
  Content,
  Footer,
  Group,
  GroupHeader,
  Items,
  Item,
  ExpandableItem,
  SubmenuItem,
  DrilldownItem,
  TreeItem,
  Separator,
} from './parts';

export const Sidebar = {
  useSidebar,
  Provider,
  Root,
  Trigger,
  Header,
  Content,
  Footer,
  Group,
  GroupHeader,
  Items,
  Item,
  ExpandableItem,
  SubmenuItem,
  DrilldownItem,
  TreeItem,
  Separator,
};

export type {
  ProviderProps as SidebarProviderProps,
  RootProps as SidebarRootProps,
  TriggerProps as SidebarTriggerProps,
  HeaderProps as SidebarHeaderProps,
  ContentProps as SidebarContentProps,
  FooterProps as SidebarFooterProps,
  GroupProps as SidebarGroupProps,
  GroupHeaderProps as SidebarGroupHeaderProps,
  ItemsProps as SidebarItemsProps,
  ItemProps as SidebarItemProps,
  ExpandableItemProps as SidebarExpandableItemProps,
  SubmenuItemProps as SidebarSubmenuItemProps,
  DrilldownItemProps as SidebarDrilldownItemProps,
  TreeItemProps as SidebarTreeItemProps,
  SeparatorProps as SidebarSeparatorProps,
} from './parts';
